services:
  db:
    container_name: security21august25
    image: postgres:latest
    environment:
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5330:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
